# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "download_references"
description: Download reference genome, GTF, and transcriptome files from S3 bucket
keywords:
  - reference
  - genome
  - transcriptome
  - download
  - s3
tools:
  - "aws-cli":
      description: "AWS Command Line Interface for downloading files from S3"
      homepage: "https://aws.amazon.com/cli/"

input: []

output:
  - genome_fasta:
      type: file
      description: Reference genome FASTA file
      pattern: "*.fa"
  - gtf:
      type: file
      description: Gene annotation GTF file
      pattern: "*.gtf"
  - transcriptome_fasta:
      type: file
      description: Transcriptome FASTA file
      pattern: "*.fa"
  - rsem_index_files:
      type: directory
      description: RSEM index files directory
      pattern: "RSEM_Genome/*"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@your-username"
maintainers:
  - "@your-username"