repository_type: pipeline

nf_core_version: 3.3.2

lint:
  files_unchanged:
    - LICENSE
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-modulestesting_logo_light.png
    - docs/images/nf-core-modulestesting_logo_light.png
    - docs/images/nf-core-modulestesting_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - LICENSE
    - CHANGELOG.md
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - .github/workflows/branch.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-modulestesting_logo_light.png
    - docs/images/nf-core-modulestesting_logo_light.png
    - docs/images/nf-core-modulestesting_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: Motleybio-organization
  name: modulestesting
  description: Testing a simplified usage of nf-core modules to see what we can stand
    up
  author: Marcus Viscardi
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - changelog
    - license
    - ci
    - igenomes
    - seqera_platform
    - gpu
    - gitpod
    - codespaces
    - vscode
    - documentation
    - rocrate
    - adaptivecard
  is_nfcore: false
